# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(max_length=256)),
                ('words', models.IntegerField()),
                ('ctime', models.IntegerField()),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('desc', models.TextField()),
                ('author', models.CharField(max_length=16)),
                ('noveltype', models.CharField(max_length=16)),
                ('tags', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'novel',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'text',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Text'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Novel'),
        ),
    ]
